<p id="back-top">
		<a href="javascript:void(0);"><span></span>Back to Top</a>
	</p>
	<div class="header-top-container">
		<div class="header-top container">
			<div class="span12">
				<div class="span6">
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('top_links')->toHtml() ?> 
				</div>
				<div class="search span6">

					<div class="store_languages_search_con">
						<div class="store_languages">
						<?php echo $this->getChildHtml('store_language') ?>
						</div>
						<div class="search_cotainer">
						<?php echo $this->getChildHtml('topSearch') ?>
						</div>
					</div>
				</div>

			</div>
		</div>
	</div>
<div class="header-container">
    <div class="header container">
     	<div class="span12">
        <?php if ($this->getIsHomePage()):?>
        <h1 class="logo span2"><strong><?php echo $this->getLogoAlt() ?></strong><a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a></h1>
        <?php else:?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo"><strong><?php echo $this->getLogoAlt() ?></strong><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
        <?php endif?>
        <div class="quick-access span10">
            
            <p class="welcome-msg"><?php echo $this->getWelcome() ?> <?php echo $this->getAdditionalHtml() ?>
            <?php if (! Mage::getSingleton('customer/session')->isLoggedIn()): ?>
<a class="lock" href="<?php echo $this->getUrl('') ?>customer/account/login/">Login</a>
<?php else: ?>
<a class="lock" href="<?php echo $this->getUrl('') ?>customer/account/logout/">Logout</a>
<?php endif; ?>
</p>
            <?php echo $this->getChildHtml('topLinks') ?>
            
        </div>
        </div>
        <?php echo $this->getChildHtml('topContainer'); ?>
    </div>
</div>
<?php echo $this->getChildHtml('topMenu') ?>
<?php $routeName = Mage::app()->getRequest()->getRouteName();
$identifier = Mage::getSingleton('cms/page')->getIdentifier(); ?>
<?php // if ($this->getIsHomePage()):?>
<?php if($routeName == 'cms' && $identifier == 'home'): ?>
<div class="home_banner_container">
<div class="home_banner container">
<div id="myCarousel" class="carousel_no slide">
<div class="carousel-inner"> 
<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('banner')->toHtml() ?> 
</div>
<!--<a class="carousel-control left" href="#myCarousel" data-slide="prev">â?¹</a>  
  <a class="carousel-control right" href="#myCarousel" data-slide="next">â?º</a>--> 
</div>
</div>
</div>
<?php endif?>

