<?php if($toplinks && is_array($toplinks)): ?>
<ul class="links">
    <?php echo $this->getChildHtml() ?>
    <?php $i=0; foreach($toplinks as $_toplink): $i++;?>
    <li class="toplink<?php echo $i;?><?php if($_toplink['first']||$_toplink['last']): ?> <?php if($_toplink['first']): ?>first<?php endif; ?><?php if($_toplink['last']): ?> last<?php endif; ?><?php endif; ?>" <?php echo $_toplink['liParams'] ?>><?php echo $_toplink['beforeText'] ?><a <?php echo $_toplink['aParams'] ?>><?php echo $_toplink['innerText'] ?></a><?php echo $_toplink['afterText'] ?></li>
    <?php endforeach; ?>
</ul>
<?php endif; ?>
